//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSIntegrations.SMSServiceNSP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceNSP.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultiSMS", ReplyAction="http://tempuri.org/IService1/GetMultiSMSResponse")]
        string[] GetMultiSMS(string MobileNo, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultiSMS", ReplyAction="http://tempuri.org/IService1/GetMultiSMSResponse")]
        System.Threading.Tasks.Task<string[]> GetMultiSMSAsync(string MobileNo, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailData", ReplyAction="http://tempuri.org/IService1/GetEmailDataResponse")]
        string GetEmailData(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailData", ReplyAction="http://tempuri.org/IService1/GetEmailDataResponse")]
        System.Threading.Tasks.Task<string> GetEmailDataAsync(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailDataMultiAttach", ReplyAction="http://tempuri.org/IService1/GetEmailDataMultiAttachResponse")]
        string GetEmailDataMultiAttach(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailDataMultiAttach", ReplyAction="http://tempuri.org/IService1/GetEmailDataMultiAttachResponse")]
        System.Threading.Tasks.Task<string> GetEmailDataMultiAttachAsync(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSOTP", ReplyAction="http://tempuri.org/IService1/GetSMSOTPResponse")]
        string GetSMSOTP(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSOTP", ReplyAction="http://tempuri.org/IService1/GetSMSOTPResponse")]
        System.Threading.Tasks.Task<string> GetSMSOTPAsync(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSData", ReplyAction="http://tempuri.org/IService1/GetSMSDataResponse")]
        string GetSMSData(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSData", ReplyAction="http://tempuri.org/IService1/GetSMSDataResponse")]
        System.Threading.Tasks.Task<string> GetSMSDataAsync(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSShorten", ReplyAction="http://tempuri.org/IService1/GetSMSShortenResponse")]
        string GetSMSShorten(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSMSShorten", ReplyAction="http://tempuri.org/IService1/GetSMSShortenResponse")]
        System.Threading.Tasks.Task<string> GetSMSShortenAsync(string mobileNo, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPolicyData", ReplyAction="http://tempuri.org/IService1/GetPolicyDataResponse")]
        string GetPolicyData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPolicyData", ReplyAction="http://tempuri.org/IService1/GetPolicyDataResponse")]
        System.Threading.Tasks.Task<string> GetPolicyDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMailWithAttachmentFrmURL", ReplyAction="http://tempuri.org/IService1/SendMailWithAttachmentFrmURLResponse")]
        string SendMailWithAttachmentFrmURL(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMailWithAttachmentFrmURL", ReplyAction="http://tempuri.org/IService1/SendMailWithAttachmentFrmURLResponse")]
        System.Threading.Tasks.Task<string> SendMailWithAttachmentFrmURLAsync(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMailWithMultiAttachmentFrmURL", ReplyAction="http://tempuri.org/IService1/SendMailWithMultiAttachmentFrmURLResponse")]
        string SendMailWithMultiAttachmentFrmURL(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMailWithMultiAttachmentFrmURL", ReplyAction="http://tempuri.org/IService1/SendMailWithMultiAttachmentFrmURLResponse")]
        System.Threading.Tasks.Task<string> SendMailWithMultiAttachmentFrmURLAsync(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SMSIntegrations.SMSServiceNSP.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SMSIntegrations.SMSServiceNSP.IService1>, SMSIntegrations.SMSServiceNSP.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetMultiSMS(string MobileNo, string text) {
            return base.Channel.GetMultiSMS(MobileNo, text);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMultiSMSAsync(string MobileNo, string text) {
            return base.Channel.GetMultiSMSAsync(MobileNo, text);
        }
        
        public string GetEmailData(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml) {
            return base.Channel.GetEmailData(From, To, CC, Subject, Body, Attachement, Fileformat, Filename, IsBodyHtml);
        }
        
        public System.Threading.Tasks.Task<string> GetEmailDataAsync(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml) {
            return base.Channel.GetEmailDataAsync(From, To, CC, Subject, Body, Attachement, Fileformat, Filename, IsBodyHtml);
        }
        
        public string GetEmailDataMultiAttach(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml) {
            return base.Channel.GetEmailDataMultiAttach(From, To, CC, Subject, Body, Attachement, Fileformat, Filename, IsBodyHtml);
        }
        
        public System.Threading.Tasks.Task<string> GetEmailDataMultiAttachAsync(string From, string To, string CC, string Subject, string Body, string Attachement, string Fileformat, string Filename, bool IsBodyHtml) {
            return base.Channel.GetEmailDataMultiAttachAsync(From, To, CC, Subject, Body, Attachement, Fileformat, Filename, IsBodyHtml);
        }
        
        public string GetSMSOTP(string mobileNo, string sms) {
            return base.Channel.GetSMSOTP(mobileNo, sms);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSOTPAsync(string mobileNo, string sms) {
            return base.Channel.GetSMSOTPAsync(mobileNo, sms);
        }
        
        public string GetSMSData(string mobileNo, string sms) {
            return base.Channel.GetSMSData(mobileNo, sms);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSDataAsync(string mobileNo, string sms) {
            return base.Channel.GetSMSDataAsync(mobileNo, sms);
        }
        
        public string GetSMSShorten(string mobileNo, string sms) {
            return base.Channel.GetSMSShorten(mobileNo, sms);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSShortenAsync(string mobileNo, string sms) {
            return base.Channel.GetSMSShortenAsync(mobileNo, sms);
        }
        
        public string GetPolicyData() {
            return base.Channel.GetPolicyData();
        }
        
        public System.Threading.Tasks.Task<string> GetPolicyDataAsync() {
            return base.Channel.GetPolicyDataAsync();
        }
        
        public string SendMailWithAttachmentFrmURL(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml) {
            return base.Channel.SendMailWithAttachmentFrmURL(From, To, CC, Subject, Body, url, filename, Fileformat, IsBodyHtml);
        }
        
        public System.Threading.Tasks.Task<string> SendMailWithAttachmentFrmURLAsync(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml) {
            return base.Channel.SendMailWithAttachmentFrmURLAsync(From, To, CC, Subject, Body, url, filename, Fileformat, IsBodyHtml);
        }
        
        public string SendMailWithMultiAttachmentFrmURL(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml) {
            return base.Channel.SendMailWithMultiAttachmentFrmURL(From, To, CC, Subject, Body, url, filename, Fileformat, IsBodyHtml);
        }
        
        public System.Threading.Tasks.Task<string> SendMailWithMultiAttachmentFrmURLAsync(string From, string To, string CC, string Subject, string Body, string url, string filename, string Fileformat, bool IsBodyHtml) {
            return base.Channel.SendMailWithMultiAttachmentFrmURLAsync(From, To, CC, Subject, Body, url, filename, Fileformat, IsBodyHtml);
        }
    }
}
